name: Publish NuGet Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          $env:TAG_VERSION=git describe --tags --abbrev=0
          msbuild RawCanvasUI.sln /t:restore
          msbuild RawCanvasUI.sln /p:Configuration=Release /p:Platform=x64 /p:Version="$env:TAG_VERSION"

      - name: Push Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          cd bin/Release/
          dotnet nuget push RawCanvasUI.*.nupkg --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json